### ISSUE TITLE
multiple same name meta keys?

### ISSUE THREAD

**Issue by ssuess** [EvanHerman/wp-rest-api-controller#4]
Hi, and thanks for this great plugin. But I notice it is only returning the first index of a meta value, is there a way to make it return all meta for a given post?

**Comment by kpu23** [comment]
Hello,

Before I test/fix this, is your meta data saved as multiple database entries with the same meta key?

Kevin.

P.S. If I'm correct in assuming it was you who left us such a nice MailChimp review, thanks a million!

**Comment by ssuess** [comment]
it was me, you guys have done fantastic work with this plugin, highly appreciated!  

And yes, I have a number entries in the postmeta table that are duplicative so that I can get them via index (I am working with piklist and it stores things this way). So for example I have a cpt that I add groups of actions to, and each action contains all possible fields (The way piklist does it).

So something like:

Main CPT

action_postmeta_name : first action 
action_postmeta_type : jump 
action_postmeta_name : second action 
action_postmeta_type : run 
action_postmeta_name : third action 
action_postmeta_type : walk

When I pull the post and all its metadata, I know that all fields are in order, so I use that index to keep the proper ones associated with each other (ie I know that first action is jump, second action is run, etc)

Hope that all makes sense.

**Comment by kpu23** [comment]
I fully understand - I'll test now and get back to you. 

Thanks for your patience!

**Comment by ssuess** [comment]
Thank you!

**Comment by kpu23** [comment]
Hello,

I'm not sure how technically oriented you are, but I'm going to explain the issue here. I apologize if it's unclear or unintelligible. We're currently calling the `get_post_meta()` function with the `$single` argument set to `true`. This means we will only retrieve one metadata field. This works for all use cases except yours (which is a pretty common use case). However, if I set `$single = false`, then fields that do not have multiple keys (i.e. one key, one value) will be returned as arrays. Because other people using this plugin may be relying on the current data structure, I'm going to add a filter that allows you to turn on/turn off the retrieval of post meta as arrays. 

This means that if you want to retrieve all of the values for a repeating meta key (your use case), you should use this filter and return `false`. I'm including the meta_key name as an argument in the filter, so if you'd like the current functionality to stay the same, but you want to retrieve repeating meta fields correctly (as arrays), then you can use a conditional to return `false` only for a specific meta key.

This post is getting a bit long so I'm going to write out the filter explanation in another comment.

Kevin.

**Comment by ssuess** [comment]
That makes perfect sense to me actually.(And If you wouldn't mind giving me a simple example of how to set this filter to always use false, I would appreciate it). Thanks for such a rapid response!

**Comment by kpu23** [comment]
The filter:
Name: `wp_rest_api_controller_retrieve_meta_single`
Parameters: 
- `$single` - this is the true / false value corresponding to the `get_post_meta()` $single argument as explained above
- `$renamed_meta_key_name` - If you've renamed your meta key, this is the new name. If you haven't renamed, this is the original name.
- `$original_meta_key_name` - this is the original meta key name

Example function:
```
function toggle_retrieving_single_post_meta( $single, $renamed_meta_key_name, $original_meta_key_name ) {

	// An example using the original meta key name
	if ( $original_meta_key_name === 'cats_repeating_test_key' ) {
		return false;
	}

	// An example using the renamed meta key name
	if ( $renamed_meta_key_name === 'cats_repeating_test_key_renamed' ) {
		return false;
	}

	// Make sure to return the original value if none of our conditionals are hit
	return $single;
}

add_filter( 'wp_rest_api_controller_retrieve_meta_single', 'toggle_retrieving_single_post_meta', 10, 3 );
```
In the above example, I'm looking for a meta key named `cats_repeating_test_key` and returning false - meaning I will retrieve all of the post meta values.

For your use case, you can replace `cats_repeating_test_key` with the value of your meta key. Note that you don't need to use both the original name and the renamed name - use which ever one you feel more comfortable with.

I'm committing the new version of the plugin now. Let me know if you need more help!
Kevin.

**Comment by kpu23** [comment]
If you'd like to return false in all situations, you can use this:

```
function toggle_retrieving_single_post_meta( $single, $renamed_meta_key_name, $original_meta_key_name ) {
	return false;
}

add_filter( 'wp_rest_api_controller_retrieve_meta_single', 'toggle_retrieving_single_post_meta', 10, 3 );
```

**Comment by kpu23** [comment]
I'll let you know when the newest version is committed :-)

**Comment by ssuess** [comment]
thanks!!

**Comment by kpu23** [comment]
v1.4.1 is committed to the WP repo. It may take a minute for your installation to recognize the update.

Please let me know that it works as I described!

Cheers,
Kevin.

**Comment by ssuess** [comment]
I will test it out and get back to you with any issues. Thanks again.

**Comment by ssuess** [comment]
so far it works and is awesome!

**Comment by kpu23** [comment]
I'm so glad. Thanks for bringing this to our attention. I'm going to close this ticket, but feel free to create a new one or continue with this thread if it's related.

Have a great day!
Kevin.
